// Mastering rack state: the live params, the pristine defaults captured
// before anything is applied, and the built-in chains.
//
// Order matters here — MASTERING_DEFAULT_PARAMS snapshots MASTERING.params
// at module load, and the factory presets spread that snapshot, so all
// three must stay in this sequence.

import { MASTERING_HQ_STORAGE_KEY } from '../core/storage.js';

export const MASTERING = {
  built: false,
  // HQ render: chain runs offline at 2× rate, then downsamples. Slower
  // render, cleaner nonlinear stages, true-peak metering. Preview untouched.
  renderHq: localStorage.getItem(MASTERING_HQ_STORAGE_KEY) === 'on',
  source: null, // { left, right, sampleRate, name }
  sourceLufs: null, // integrated LUFS of the raw source (bypass loudness match)
  renderedLufs: null, // integrated LUFS of the last render (bypass loudness match)
  params: {
    lowGain: 0,
    lowFreq: 120,
    lowQ: 0.7,
    lowType: 'peak', // 'peak' bell · 'cut' 12 dB/oct high-pass (gain/dyn unused)
    lowDynThresh: 0,
    lowDynRange: 0,
    lowMidGain: 0,
    lowMidFreq: 350,
    lowMidQ: 1,
    lowMidDynThresh: 0,
    lowMidDynRange: 0,
    midGain: 0,
    midFreq: 900,
    midQ: 0.7,
    midDynThresh: 0,
    midDynRange: 0,
    highMidGain: 0,
    highMidFreq: 3000,
    highMidQ: 1,
    highMidDynThresh: 0,
    highMidDynRange: 0,
    highGain: 0,
    highFreq: 8000,
    highQ: 0.7,
    highDynThresh: 0,
    highDynRange: 0,
    compThreshold: -18,
    compRatio: 2,
    compAttack: 0.03,
    compRelease: 0.25,
    compMakeup: 0,
    optoReduction: 0,
    optoMakeup: 0,
    optoMode: '2a',
    tapeDrive: 0,
    tapeBump: 0,
    tapeRolloff: 20,
    tapeLevel: 0,
    excTune: 3000,
    excHarmonics: 0,
    excMix: 0,
    ottDepth: 0,
    ottTime: 1,
    ottIn: 0,
    ottOut: 0,
    ottLow: 0,
    ottMid: 0,
    ottHigh: 0,
    subTune: 80,
    subAmount: 0,
    subMix: 0,
    levelerGain: 0, // input trim — always the first thing the signal meets
    rawLevelerGain: 0, // bypass-path makeup gain (raw A/B leveler); never renders
    width: 1,
    widthBassFreq: 0, // 0 = full-range; raise it to keep lows mono when widening
    enabled: { eq: true, opto: true, comp: true, ott: true, tape: true, sub: true, exciter: true, width: true, limit: true },
    drive: 0,
    ceiling: -1,
    outGain: 0,
    order: ['eq', 'opto', 'comp', 'ott', 'tape', 'sub', 'exciter', 'width', 'limit'],
  },
  ctx: null, // preview AudioContext — created on demand, suspended on view exit
  preview: null, // { srcNode, chain, analysers, startAt, duration }
  previewBuffer: null, // AudioBuffer cache for the current source
  renderedPeaks: null, // decimated min/max envelope of the last offline render
  vizFrame: null, // rAF id — only ever set while preview is playing
  meterHover: null, // { x, y } in CSS px over the meter canvas, null when pointer is outside
  eqHover: null, // { x, y } in CSS px over the EQ canvas, null when pointer is outside
  eqBandIndex: 0,
  eqSolo: false,
  playheadSec: 0,
  loopMode: 'off', // off | section | all
  loopSelection: null, // { start, end } in seconds
  els: {},
};

export const MASTERING_MODULE_IDS = ['eq', 'opto', 'comp', 'ott', 'tape', 'sub', 'exciter', 'width', 'limit'];

export const MASTERING_DEFAULT_PARAMS = JSON.parse(JSON.stringify(MASTERING.params));

// Built-in mastering chains. Keep these as complete parameter snapshots so
// adding a module later falls back safely through applyMasteringPreset().
export const MASTERING_FACTORY_PRESETS = [
  {
    id: 'preset-1',
    name: 'Preset 1',
    params: {
      ...MASTERING_DEFAULT_PARAMS,
      levelerGain: -3.5,
      lowGain: -9,
      lowFreq: 20,
      lowQ: 0.7,
      lowMidGain: -0.5,
      lowMidFreq: 90,
      lowMidQ: 1,
      midGain: 0,
      midFreq: 900,
      midQ: 0.7,
      highMidGain: 0,
      highMidFreq: 2900,
      highMidQ: 1,
      highGain: -1,
      highFreq: 10000,
      highQ: 0.7,
      highDynThresh: -18,
      highDynRange: 3.5,
      optoReduction: 3.5,
      optoMakeup: 2.5,
      optoMode: '2a',
      compThreshold: -18,
      compRatio: 2,
      compAttack: 0.03,
      compRelease: 0.25,
      compMakeup: 1,
      ottDepth: 15,
      ottTime: 0.95,
      ottIn: 1.5,
      ottOut: 1.5,
      ottLow: 2.5,
      ottMid: 3.5,
      ottHigh: 0,
      tapeDrive: 1,
      tapeBump: 0.5,
      tapeRolloff: 20,
      tapeLevel: 0.5,
      subTune: 40,
      subAmount: 8.5,
      subMix: 8,
      excTune: 5000,
      excHarmonics: 14,
      excMix: 9,
      width: 1.6,
      widthBassFreq: 300,
      drive: 0,
      ceiling: -1,
      outGain: 0,
      enabled: { ...MASTERING_DEFAULT_PARAMS.enabled },
      order: [...MASTERING_DEFAULT_PARAMS.order],
    },
  },
  {
    id: 'preset-2',
    name: 'Preset 2',
    params: {
      ...MASTERING_DEFAULT_PARAMS,
      levelerGain: -5.5,
      lowGain: -8.5,
      lowFreq: 20,
      lowQ: 0.7,
      lowMidGain: 1,
      lowMidFreq: 80,
      lowMidQ: 1,
      midGain: -2.5,
      midFreq: 200,
      midQ: 0.7,
      highMidGain: 1.5,
      highMidFreq: 3000,
      highMidQ: 1,
      highGain: 0,
      highFreq: 10000,
      highQ: 0.7,
      highDynThresh: -18,
      highDynRange: 4,
      optoReduction: 7.5,
      optoMakeup: 4.5,
      optoMode: '2a',
      compThreshold: -16.5,
      compRatio: 3,
      compAttack: 0.03,
      compRelease: 0.25,
      compMakeup: 2,
      ottDepth: 29,
      ottTime: 0.95,
      ottIn: 1.5,
      ottOut: 1.5,
      ottLow: 1,
      ottMid: 5.5,
      ottHigh: -4,
      tapeDrive: 1.5,
      tapeBump: 1,
      tapeRolloff: 16,
      tapeLevel: 1.5,
      subTune: 50,
      subAmount: 6.5,
      subMix: 11,
      excTune: 3400,
      excHarmonics: 16.5,
      excMix: 11,
      width: 1.8,
      widthBassFreq: 270,
      drive: 1,
      ceiling: -0.5,
      outGain: 0,
      enabled: { ...MASTERING_DEFAULT_PARAMS.enabled },
      order: [...MASTERING_DEFAULT_PARAMS.order],
    },
  },
  {
    id: 'preset-3',
    name: 'Preset 3',
    params: {
      ...MASTERING_DEFAULT_PARAMS,
      levelerGain: -2,
      lowType: 'cut',
      lowGain: 0,
      lowFreq: 35,
      lowQ: 0.7,
      lowMidGain: 1,
      lowMidFreq: 80,
      lowMidQ: 1,
      midGain: 0.5,
      midFreq: 250,
      midQ: 0.7,
      highMidGain: 1.5,
      highMidFreq: 3000,
      highMidQ: 1,
      highGain: -1,
      highFreq: 13640,
      highQ: 0.7,
      highDynThresh: -22,
      highDynRange: 5.9,
      optoReduction: 6,
      optoMakeup: 3,
      optoMode: '3a',
      compThreshold: -27,
      compRatio: 3,
      compAttack: 0.019,
      compRelease: 0.2,
      compMakeup: 1.5,
      ottDepth: 23,
      ottTime: 0.95,
      ottIn: 1.5,
      ottOut: 1.5,
      ottLow: 1,
      ottMid: 0.5,
      ottHigh: 2.5,
      tapeDrive: 1,
      tapeBump: 0.5,
      tapeRolloff: 20,
      tapeLevel: 1,
      subTune: 50,
      subAmount: 2,
      subMix: 7,
      excTune: 3400,
      excHarmonics: 16.5,
      excMix: 11,
      width: 1.4,
      widthBassFreq: 230,
      drive: 1,
      ceiling: -1,
      outGain: 0,
      enabled: { ...MASTERING_DEFAULT_PARAMS.enabled },
      order: ['sub', 'eq', 'ott', 'width', 'opto', 'comp', 'tape', 'exciter', 'limit'],
    },
  },
  {
    id: 'preset-4',
    name: 'Preset 4',
    params: {
      ...MASTERING_DEFAULT_PARAMS,
      levelerGain: -9,
      lowType: 'cut',
      lowGain: 0,
      lowFreq: 36,
      lowQ: 0.7,
      lowMidGain: 2.5,
      lowMidFreq: 100,
      lowMidQ: 1,
      midGain: -3.5,
      midFreq: 200,
      midQ: 0.7,
      highMidGain: 1.5,
      highMidFreq: 1250,
      highMidQ: 1,
      highGain: -2.5,
      highFreq: 8980,
      highQ: 0.5,
      highDynThresh: -31,
      highDynRange: 4,
      optoReduction: 8,
      optoMakeup: 8,
      optoMode: '3a',
      compThreshold: -15,
      compRatio: 3,
      compAttack: 0.019,
      compRelease: 0.2,
      compMakeup: 1.5,
      ottDepth: 23,
      ottTime: 0.95,
      ottIn: 1.5,
      ottOut: 1.5,
      ottLow: 3,
      ottMid: 0.5,
      ottHigh: -1,
      tapeDrive: 1,
      tapeBump: 0.5,
      tapeRolloff: 20,
      tapeLevel: 1,
      subTune: 55,
      subAmount: 3,
      subMix: 18,
      excTune: 8000,
      excHarmonics: 20.5,
      excMix: 11,
      width: 1.6,
      widthBassFreq: 260,
      drive: 1.5,
      ceiling: -1,
      outGain: 0,
      enabled: { ...MASTERING_DEFAULT_PARAMS.enabled },
      order: ['sub', 'eq', 'tape', 'ott', 'width', 'opto', 'comp', 'exciter', 'limit'],
    },
  },
];
